# Generated by Django 3.0.5 on 2020-06-08 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0010_auto_20200607_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='idSeller',
            new_name='idseller',
        ),
    ]
