# Generated by Django 3.0.5 on 2020-06-02 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('idMensaje', models.AutoField(primary_key=True, serialize=False, verbose_name='idMensaje')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('subject', models.TextField(max_length=50, verbose_name='Asunto')),
                ('message', models.TextField(max_length=1000, verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idProduct', models.AutoField(primary_key=True, serialize=False, verbose_name='IdProducto')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('description', models.TextField(max_length=50, verbose_name='Descripcion')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('idsell', models.AutoField(primary_key=True, serialize=False, verbose_name='IdVenta')),
                ('totalProducts', models.IntegerField(verbose_name='TotalProductos')),
                ('total', models.IntegerField(verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('idSeller', models.AutoField(primary_key=True, serialize=False, verbose_name='idVendedor')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=50, verbose_name='Apellido')),
                ('numBoleta', models.IntegerField(verbose_name='Boleta')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('password', models.CharField(max_length=16, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('idshopper', models.AutoField(primary_key=True, serialize=False, verbose_name='IdComprador')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=50, verbose_name='Apellido')),
                ('numBoleta', models.IntegerField(verbose_name='Boleta')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('password', models.CharField(max_length=16, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'Comprador',
                'verbose_name_plural': 'Compradores',
            },
        ),
        migrations.CreateModel(
            name='SellProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.Product', verbose_name='Idproducto')),
                ('idseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.Seller', verbose_name='IdVendedor')),
            ],
            options={
                'verbose_name': 'VendProducto',
                'verbose_name_plural': 'VendProductos',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idsell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.Sell', verbose_name='IdVenta')),
                ('idshopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.Shopper', verbose_name='IdComprador')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
