# Generated by Django 3.0.5 on 2020-06-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_auto_20200604_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
