# Generated by Django 3.0.5 on 2020-06-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_auto_20200604_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='articulos'),
        ),
    ]
