# Generated by Django 3.0.5 on 2020-06-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0009_auto_20200605_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='image',
            field=models.ImageField(default='null', upload_to='media'),
        ),
        migrations.AddField(
            model_name='shopper',
            name='image',
            field=models.ImageField(default='null', upload_to='media'),
        ),
    ]
