# Generated by Django 3.0.5 on 2020-06-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0011_auto_20200607_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='idProduct',
            new_name='idproduct',
        ),
    ]
